---
repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.10
    entry: black .
    args:
    - --config=pyproject.toml
    - --skip-string-normalization
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
    language_version: python3.10
    entry: bash -c 'bandit . || true' --
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-xml
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: end-of-file-fixer
    exclude: .json|.graphql
  - id: double-quote-string-fixer
  - id: detect-private-key
  - id: debug-statements
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
  - id: autopep8
    args:
    - --diff
    - --recursive
    - --max-line-length=120
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    entry: pflake8
    additional_dependencies: [
      'pyproject-flake8',
      'flake8-absolute-import',
      'flake8-aaa',
      'flake8-bugbear',
      'flake8-walrus',
#      'flake8-cognitive-complexity',
      'flake8-pep3101',
      #'flake8-annotations',
      'flake8-pie',
      'flake8-print',
      'flake8-printf-formatting',
      'flake8-pytest',
      #'flake8-pytest-style',
      'flake8-simplify',
      'flake8-use-fstring',
      'flake8-variables-names',
    ]
