---
version : '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - 8000:8000
    env_file:
    - ./.env
    volumes:
    - .:/app/src/
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: backend
      DB_PASS: backend
      DB_BASE: backend

  db:
    image: postgres:13.6-bullseye
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: backend
      POSTGRES_USER: backend
      POSTGRES_DB: backend
    volumes:
    - backend-db-data:/var/lib/postgresql/data
    restart: always
    command: [postgres, -c, log_statement=all, -c, log_destination=stderr]
    healthcheck:
      test: pg_isready -U backend
      interval: 2s
      timeout: 3s
      retries: 40


volumes :
  backend-db-data:
    name: backend-db-data
